import pandas as pd

lines = [
    "cingur, kornet, sosis, abon, iga sapi, tetelan, kikil, sapi, sirloin, tenderloin : daging sapi",
    "rumput laut, nori, seaweed : rumput laut",
    "timun, mentimun : timun",
    "kacang tanah : kacang tanah",
    "cabe rawit, lombok rawit, cabai rawit : cabe rawit",
    "petis : petis",
    "gula merah, gula merahg : gula merah",
    "garam, himalaya salt, himsalt : garam",
    "air asam, air asem : air asam",
    "kangkung : kangkung",
    "terasi, trasi : terasi",
    "air jeruk limau : air jeruk",
    "lengkuas : lengkuas",
    "jahe : jahe",
    "kunyit : kunyit",
    "serai, sereh, batang serai, serei, sere, sereh, sre : serai",
    "daun salam, salam : daun salam",
    "daun jeruk , dain jeruk: daun jeruk",
    "kecap manis, kecap : kecap",
    "minyak goreng, minyak, minyak sayur, oil, minyak goreng, minyak kelapa, minyak sayur : minyak",
    "petisopsional, petis : petis",
    "tomat, cung kediro, cungkediro, cungdiro : tomat",
    "labu siam, sayuranlabu, waluh : labu",
    "kacang panjang : kacang panjang",
    "jagung manis : jagung",
    "daun melinjo, daun mlinjo : daun melinjo",
    "asam jawa, asem jawa : asam",
    "tahu : tahu",
    "tauge, toge, taoge, kecambah, cambah : tauge",
    "telur rebus, telur, telur, telur ayam, kuning telur, putih telur : telur",
    "kol : kol",
    "bawang putih, bawang putih bubuk, bawang putih goreng : bawang putih",
    "bawang goreng, bawang peking : bawang merah",
    "bumbu kacang : kacang tanah",
    "ketumbar, tumbar : ketumbar",
    "kemiri, miri : kemiri",
    "kentang : kentang",
    "telur, telor : telur",
    "bawang bombay, bawang bombai, bombay, bombai : bawang bombay",
    "krupuk, kerupuk : kerupuk",
    "nasi : beras",
    "ayam suwir, ati, ampela, ceker, ayam, kaldu rasa ayam, kaldu ayam, dada ayam, paha ayam, ayam kampung : daging ayam",
    "parutan kelapa, santan, serundeng kelapa, air kelapa, santen : kelapa",
    "lele, ikan, ikan tongkol, ikan pe, ikan patin, ikan pindang, pindang, ikan nila, nila, ikan teri, teri, salmon, tuna, baung, iwak, kembung, tongkol, pindang, tengiri, tenggiri, sarden, ikan mas, bandeng, tuna, ikan kakap, ikan tenggiri, ikan : ikan",
    "wortel : wortel",
    "tempe, gembus : tempe",
    "kacang panjang : kacang panjang",
    "cabai, lombok merah, cabe merah , cabai merah, cabe, lombok, cabai keriting, cabe keriting, cabai kriting, cabe kriting, cabe gendot : cabai merah",
    "ketumbar, tumbar : ketumbar",
    "bayam : bayam",
    "jagung : jagung",
    "kunci : kunci",
    "jamur tiram, jamur, bubuk jamur, bubuk penyedap jamur, kaldu jamur, kaldu rasa jamur : jamur",
    "daun bawang, bawang pre, daun prey, daun pre : daun bawang",
    "merica, mrica : merica",
    "daun pisang : daun pisang",
    "kangkung : kangkung",
    "pisang : pisang",
    "jahe : jahe",
    "ketupat, lontong, beras : beras",
    "penyedap, penyedap rasa, kaldu bubuk, bumbu marinasi, bumbu desaku, bumbu instan, kaldu instan, kobe, totole, msg, micin, royco, masako, aji nomoto : penyedap rasa",
    "bebek : daging bebek",
    "es batu, air : air",
    "tepung tapioka : tepung",
    "baking powder : baking powder",
    "seledri, selederi, slederi, sledri, seledry : seledri",
    "kulit pangsit : tepung",
    "saos, saus : saos",
    "sawi hijau, sawi putiih : sawi",
    "nangka, gorinangka, gori, tewel : nangka",
    "daun jati : daun jati",
    "sayap ayam, cakar ayam, hati ayam, paru : daging ayam",
    "gula pasir, gula, gula pasir, stevia, sweetener : gula",
    "kaldu jamur : kaldu jamur",
    "daun pisang : daun pisang",
    "teh, thai tea : teh",
    "laos : laos",
    "air kelapa, air nira : air kelapa",
    "gula aren : gula aren",
    "mie, mie kuning, mi kuning, mie kering, mi kering : mie",
    "lada putih, lada hitam, bubuk lada, lada bubuk, lada : lada",
    "saus tiram, saos tiram, saori : saos tiram",
    "kecap asin : kecap asin",
    "ebi, rebung, udang  : udang",
    "daun serai, daun sereh : daun serai",
    "jeruk nipis, jeruk, nipis, limau, lemo : jeruk nipis",
    "kencur : kencur",
    "kangkung : kangkung",
    "kacang panjang : kacang panjang",
    "belimbing, blimbing : belimbing",
    "kol : kol",
    "cabe hijau, cabai hijau, cabe ijo, cabai ijo : cabai hijau",
    "ketan : ketan",
    "gula palm : gula palm",
    "daun pandan, pandan : daun pandan",
    "oncom : oncom",
    "jeruk purut : jeruk purut",
    "beras merah : beras merah",
    "gula jawa : gula jawa",
    "pisang : pisang",
    "bubuk vanilla, bubuk vanila, vanilla, vanila : vanilla",
    "daun kemangi : daun kemangi",
    "sukun : sukun",
    "daun kenikir : daun kenikir",
    "daun ubi, daun singkong : daun singkong",
    "bekicot : bekicot",
    "kubis, kobis : kubis",
    "bayam : bayam",
    "soda kue : soda kue",
    "tepung protein sedang, terigu, tepung terigu, tepung, kulit pangsit, kulit lumpia : tepung terigu",
    "butter, mentega, blueband, wisjman : mentega",
    "fiber creme, fibercreme, fiber cream, fibercream : gula",
    "air biasa, air putih, air hangat, air dingin, air, es : air",
    "biskuit : biskuit",
    "kental manis, susu, skm : susu",
    "margarin, margarine, blue band, blueband : margarin",
    "selada : selada",
    "cabe tanjung : cabe tanjung",
    "kluwek : kluwek",
    "jintan, jinten : jintan",
    "daging kambing, kambing : daging kambing",
    "pokcoy, pokchoy : pokcoy",
    "vanili, vanilli : vanili",
    "fermipan : fermipan",
    "gula halus, gula castor : gula",
    "pasta coklat, coklat, selai coklat, pasta cokelat, cokelat, selai cokelat, choco chip, meises, mesis : coklat",
    "telur puyuh, telor puyuh, telur burung puyuh, telor burung puyuh : telur puyuh",
    "tepung ketan : tepung ketan",
    "daun asam : daun asam",
    "terong, terung : terong",
    "kacang tholo, kacang tolo : kacang tholo",
    "kayu manis, kayumanis : kayu manis",
    "buncis : buncis",
    "regal : biskuit",
    "terasi, trasi : terasi",
    "jantung pisang  : jantung pisang",
    "daun beluntas : daun beluntas",
    "belut : belut",
    "kemangi, kemanggi : kemangi",
    "kapulaga : kapulaga",
    "cengkeh, cengkih : cengkeh",
    "caisin : caisin",
    "pete, petai : pete",
    "palem : palem",
    "lemon : lemon",
    "hazelnut : hazelnut",
    "grape : anggur",
    "bunga turi : bunga turi",
    "bengkuang, bengkoang : bengkoang",
    "pelepah bunga kelapa : manggar",
    "singkong, tela, ubi : ubi",
    "kunci : kunci",
    "mlinjo, melinjo, blinjo : melinjo",
    "oyong : oyong",
    "ubi : ubi",
    "pokcoy : pokcoy",
    "tempoyak : tempoyak",
    "jeruk songkit : jeruk songkit",
    "adas : adas",
    "pala : pala",
    "bunga lawang : bunga lawang",
    "umbut rotan : umbut rotan",
    "rimbang : rimbang",
    "nanas : nanas",
    "kacang hijau, kacang ijo : kacang hijau",
    "santen, santan, kara : santan",
    "pare : pare",
    "jengkol : jengkol",
    "daun mengkudu : daun mengkudu",
    "daun kesum : daun kesum",
    "duren, durian : durian",
    "cempedak : cempedak",
    "bunga kecombrang, kecombrang : kecombrang",
    "jeruk katsuri : jeruk katsuri",
    "pisang, pisang kepok : pisang",
    "beras ketan, ketan : ketan",
    "maizena, meizena : maizena",
    "pewarna : pewarna makanan",
    "baking soda : baking soda",
    "brown sugar : brown sugar",
    "sirup, sirop, perisan, syrup : sirup",
    "daun bay : daun bay",
    "roti : roti",
    "daging kuda, kuda : daging kuda",
    "soun, bihun : bihun",
    "yeast : yeast",
    "daun kelor, sayur kelor, kelor : daun kelor",
    "keju : keju",
    "melon : melon",
    "kacang merah : kacang merah",
    "buah naga : buah naga",
    "strawberry : strawberry",
    "tepung beras, rosebrand : tepung beras",
    "tepung ketan : tepung ketan",
    "sagu : sagu",
    "coconut sugar : coconut sugar",
    "bunga pepaya : bunga pepaya",
    "buncis : buncis",
    "daun melinjo : daun melinjo",
    "beras ketan, nasi ketan : ketan",
    "fermipan : fermipan",
    "ragi : ragi",
    "cakalang : cakalang",
    "kacang kenari : kacang kenari",
    "sirsak : sirsak",
    "alpukat : alpukat",
    "nata de coco : nata de coco",
    "biji selasih : biji selasih",
    "pepaya : pepaya",
    "akar teratai : akar teratai",
    "kacang mete : kacang mete",
    "siput : siput",
    "tepung tapioka : tepung tapioka",
    "tepung sagu : tepung sagu",
    "kenari : kenari",
    "soda kue : soda kue",
    "pare : pare",
    "caisim : sawi",
    "kwetiaw, kuetiaw, kwetiau : kwetiaw",
    "baso ikan : ikan",
    "baso sapi : sapi",
    "bunga lawang, lawang : bunga lawang",
    "daun katuk : daun katuk",
    "kerang : kerang",
    "pokcay : pokcoy",
    "kubis, kobis : kol",
    "tauco, taoco : tauco",
    "suji, daun suji : daun suji",
    "tepung tapioka, tapioka, tapioca, tepung kanji : tepung tapioka",
    "mie hun, soun, bihun : bihun",
    "kincong : daun kincong",
    "kayumanis : kayu manis",
    "matcha : matcha",
    "sugar : gula",
    "prei, daun prei : prei",
    "bunga telang : bunga telang",
    "bunga pekak, pekak : bunga pekak",
    "bakso, baso : daging sapi",
    "bakso ikan, baso ikan : ikan",
    "rimbang : terung",
    "jipang : jipang",
    "andaliman : andalima",
    "daun kari : daun kari",
    "telur bebek : telur bebek",
    "pepaya : pepaya",
    "bunga bintang : bunga bintang",
    "tutut : tutut",
    "daun temuru : daun temuru",
    "cuka : cuka",
    "gurita : gurita",
    "bebek : daging bebek",
    "cumi, cumi-cumi : cumi-cumi",
    "binjai : binjai",
    "daun ruku : daun ruku",
    "kedondong : kedondong",
    "mangga : mangga",
    "kucai : kucai",
    "tunjang : tunjang",
    "tausa : tausa",
    "agaragar, nutrijell : puding",
    "daun kedondong : daun kedondong",
    "tepung mocaf : tepung mocaf",
    "wijen : wijen",
    "kopi : kopi",
    "rampai, rempai : rampai",
    "sirih : sirih",
    "daun pakis : daun pakis",
    "lobak : lobak",
    "kepiting, karaka : kepiting",
    "wijen : wijen",
    "kacang telegis : kacang telegis",
    "kacang keplos : kacang keplos",
    "kacang mentik : kacang mentik",
    "wani : wani",
    "cuka, cuka apel : cuka",
]

data = []
for line in lines:
    padanan, kategori = line.split(':')
    kategori = kategori.strip()
    padanan_list = [p.strip() for p in padanan.split(',')]
    for p in padanan_list:
        data.append({'BAHAN': p, 'KATEGORI': kategori})

df = pd.DataFrame(data)
df.to_excel('Padanan Bahan.xlsx', index=False)

print("File 'Padanan Bahan.xlsx' berhasil dibuat.")
